# Generated by Django 4.0 on 2022-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(height_field=400, upload_to='photos/%Y/%M/', verbose_name='photo', width_field=400)),
                ('is_published', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
