# Generated by Django 4.0 on 2022-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(height_field='400px', upload_to='photos/%Y/%M/', verbose_name='photo', width_field='400px'),
        ),
    ]
