# Generated by Django 4.0 on 2022-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_height',
            field=models.PositiveIntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='url_width',
            field=models.PositiveIntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(height_field='url_height', upload_to='photos/%Y/%M/', verbose_name='photo', width_field='url_width'),
        ),
    ]
